services:
  churn-api:
    image: churn-api:latest
    ports:
      - "80:8000"
    restart: always  # Ensure the API restarts if it crashes
    environment:
      - ENV=production
      - LOG_LEVEL=INFO
      - CORS_ORIGINS=http://0.0.0.0
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M